### ISSUE TITLE
Error property 'left' is not supported by native animated module when using swipe

### ISSUE THREAD

**Issue by teddyteh** [react-native-modal/react-native-modal#163]
```
<Modal isVisible={this.state.isTimelineOpen}
                       onSwipe={() => this.setState({isTimelineOpen: false})} swipeDirection="up">
                    <Text>Test<Text/>
                </Modal>
```

Keeping it as simple as the above, I'm getting an error that says "property left is not supported by native animated module. Any ideas?

**Comment by mmazzarolo** [comment]
Are you setting other props? Seems related to react-native-animatable

**Comment by teddyteh** [comment]
Well my complete code looks like this:

`Modal isVisible={this.state.isTimelineOpen}
                       onBackButtonPress={() => this.setState({isTimelineOpen: false})}
                       onBackdropPress={() => this.setState({isTimelineOpen: false})}
                       onModalHide={() => this.setState({isTimelineOpen: false})}
                       onSwipe={() => this.setState({isTimelineOpen: false})} swipeDirection="down"
                       useNativeDriver={true} hideModalContentWhileAnimating={true} style={{margin: 0}}>
                    <Text>Test<Text/>
                </Modal>`

If you remove useNativeDriver={true}, it works.

**Comment by mmazzarolo** [comment]
I investigated a bit and I think that `useNativeDriver` currently does not support the swiping due to React-Native limitations. 
The issue might be addresses soon though thanks to all the recent contributions to the React-Native gesture system.

**Comment by erickreutz** [comment]
This is not due to react native limitations. This is a problem because `getLayout` is being used which animates the `left` and `top` style properties of a view which are not supported by `useNativeDriver`. an alternative to `getLayout` exists called `getTranslateTransform` [(See here)](https://facebook.github.io/react-native/docs/0.5/animatedvaluexy#gettranslatetransform) that animates `translateX` and `translateY` instead of `top` and `left` the but since react-native-animatable animations are using those properties to pull of the in/out transitions and react-native-animatable will override the on the view if you try and set the transform explicity this is not currently possible.

**Comment by mmazzarolo** [comment]
Thanks for expanding the discussion, re-opening.
IIRC what made me write "React-Native limitations" was exactly that `top` and `left` cannot be animated by `useNativeDriver`. Yeah, I should have been a much more explicit, my bad.  
Implementing the animations using `translateX` and `translateY` might not be straightforward since we also have to keep in mind we're using react-native-animatable.  
@erickreutz do you have any idea on how this could be solved? 🤔

**Comment by erickreutz** [comment]
The problem is that you have to define react-native-animatable animations ahead of time and don't seem to have a way to dynamically influence them or manipulate them from an interaction so I can't think of a way to solve this outside of getting rid of react-native-animatable in favor of defining the animations ourselves.

**Comment by mmazzarolo** [comment]
Gotcha. I agree. I think defining the definitions ourselves might be the best solution (replacing only the ones used on the swiping interactions).

**Comment by pongponglau** [comment]
I encounter the same issue. Using useNativeDriver is so good for smooth animation. Any idea how to fix this? Thanks a lot

**Comment by berpcor** [comment]
Any code, please?

**Comment by mmazzarolo** [comment]
@berpcor unfortunately this is still an open issue, see the comments above

**Comment by denieler** [comment]
you can use
```
{
  transform: [{
    translateX: 50
  }]
}
```
to simulate animation for the left positioning if you don't have strict restrictions about using `left` property

**Comment by denieler** [comment]
@amazing-space-invader read my previous answer

**Comment by jfrolich** [comment]
I think this issue is also happening when not animating left.

**Comment by cjroth** [comment]
Look into https://github.com/maxs15/react-native-modalbox if you absolutely need native animations for now.

**Comment by mmazzarolo** [comment]
> I think this issue is also happening when not animating left.
Yes, it is

@denieler mind expanding a bit? I understand that the `translateX` prop can be animated natively but are you proposing to make the change it directly in the modal component?  

I'm available for helping out if someone is willing to tackle the issue 👍

**Comment by cjroth** [comment]
Here's a temporary workaround if you are willing to sacrifice the the visual drag feedback in exchange for native driver animations: https://github.com/react-native-community/react-native-modal/pull/247

**Comment by mmazzarolo** [comment]
@cjroth Funny thing is, if you use an animatable animation that doesn't use the `translate` property (e.g.: `fadeIn` and `fadeOut`), the swiping animation works correctly with `getTranslateTransform` even with the `useNativeDriver={true}`. 

If there's a way to override the `translateX`/`translateY` of a react-native-animatable View we might be able to fix it in all cases (with both `nativeDriver` on and off)

**Comment by DimitryDushkin** [comment]
Looks like it is fixed in 8.0.0-beta, but now swiping is not actual dragging children anymore.

**Comment by mmazzarolo** [comment]
@DimitryDushkin Hm, I just tested it and the swiping is working fine for me (still having issues with the scrollable content though).  
Could you add a bit more details? Also, thanks for the feedback 👍

**Comment by mahdinba97** [comment]
I still have this problem: #332

**Comment by kesha-antonov** [comment]
How about using https://github.com/kmagiera/react-native-gesture-handler?

**Comment by mmazzarolo** [comment]
> How about using https://github.com/kmagiera/react-native-gesture-handler?
react-native-gesture-handler is great and I'm all for using it... someone would have to tackle it though, which is not an easy task

**Comment by kesha-antonov** [comment]
Swipe up/down is easy
Not sure how to connect backdrop though
Maybe I look into it but can't promise
