### ISSUE TITLE
The keyboard does not pop up when the Android Textinput autoFocus is true

### ISSUE THREAD

**Issue by nangongque** [react-native-modal/react-native-modal#516]
## Platforms

only happen android
## Versions

- Android:
- iOS:
- react-native-modal:11.5.3
- react-native:0.63.3
- react:

## Reproducible Demo
Here is our modal code
  <Modal
          isVisible={edit}
          style={styles.modalStyle}
          backdropTransitionOutTiming={0}
          onBackdropPress={() => this.resetState()}
          animationIn="fadeInUp"
          animationOut="fadeOutDown"
          avoidKeyboard={true}
        >
        <View
          style={{
            backgroundColor: 'white',
            width: deviceWidth,
            paddingVertical: 10,
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
          }}
        >
          <TextInput
            value={content}
            multiline={true}
            autoFocus={true}
            placeholder={'回复本帖：'}
            maxLength={140}
            ref={(ref) => (this.contentInput = ref)}
            onBlur={this.contentInputBlur}
            onFocus={this.contentInputFocus}
            underlineColorAndroid="transparent"
            onChangeText={(v) => this.setState({ content: v })}
            style={{
              height: 100,
              width: deviceWidth - 30,
              backgroundColor: '#F7F7FB',
              textAlignVertical: 'top',
              borderRadius: 8,
              alignSelf: 'center',
              padding: 15,
            }}
          />
          </View>
         </Modal>

**Comment by bekazandukeli** [comment]
It will work:
```
export default YourComponent() {
  const inputRef = React.useRef(null);
  return (
    <Modal onModalShow={() => input.current.focus()} >
      <TextInput ref={inputRef} />
    </Modal>
}
```

**Comment by jiyuan12354** [comment]
I encounterred this issue too...

**Comment by VanDu97** [comment]
It's a solution
<Modal isVisible={true} onModalShow={() => {
this.inputRef.blur();
this.inputRef.focus();
} >
      <TextInput ref={ref => inputRef = ref} />
    </Modal>

**Comment by M-i-k-e-l** [comment]
You can call only `this.inputRef.focus();` if you do something like:
```
<TextInput ref={ref => inputRef = ref} autoFocus={isAndroid ? false : props.autoFocus}/>
```

**Comment by sciamp** [comment]
Hi it looks like 11.10.0 is still affected by this.

Any hint to start working on a PR? I'm willing to help :)

**Comment by NathanBeesley** [comment]
I believe you should be able to creat a ref for the input and on mount set the focus. You may have to set a timeout/delay. You don't want to focus before the modal is fully rendered(not transitioning). I'll create a expo snack here shortly.

**Comment by JoeyFenny** [comment]
I too am having this issue.

I tried @bekazandukeli and @NathanBeesley solutions and although they seemed like they should work, they didn't work for me.

@VanDu97 solution did work for me, however I believe this is still a bug that should be fixed, because we should not have to call blur() first, before calling focus()

**Comment by ccascante87** [comment]
I am having this issue too.

I've tried all the solutions here and the one from @VanDu97 is the one with more consistency however is not working 100% in my case. I'm still seeing some occurrences of this issue.

**Comment by soncheaoe9999** [comment]
my solution delay to load modal
const inputTitle = useRef<TextInput>()
<Modal isVisible={true} onShow={() => {
const timeout = setTimeout(() => {
      inputTitle.current.focus()
    }, 100);
    return () => clearTimeout(timeout)
} >
<TextInput ref={inputTitle}/>

**Comment by hraschan** [comment]
Is somebody working on this bug? I got the same issue.

**Comment by lloydraj** [comment]
The solution seems to be to focus on it only after the modal has appeared.
  
  See code below:


Ref

`  const inputRef = useRef();
`

Focus Onshow
```
                <Modal
                    animationType="fade"
                    transparent={true}
                    visible={modalVisible}
                    onShow={()=> {
                        inputRef.current.focus();
                    }}
```


Insert Ref into TextInput

```
                                <TextInput
                                    autoFocus
                                    ref={inputRef}

				...

```

**Comment by erksch** [comment]
This took me ages to figure out

```typescript
onShow={() => {
  setTimeout(() => {
    inputRef.current?.blur();
    inputRef.current?.focus();
   }, 100);
}}
```

also works in an `useEffect`:
```typescript
useEffect(() => {
  setTimeout(() => {
    inputRef.current?.blur();
    inputRef.current?.focus();
  }, 100);
}, []);
```

And it only works when calling `.blur()` first!

**Comment by TijsM** [comment]
@erksch Thanks for the fix! For me the `.onBlur` is not needed, the timeout is

**Comment by soneratmaca00** [comment]
> my solution delay to load modal const inputTitle = useRef() <Modal isVisible={true} onShow={() => { const timeout = setTimeout(() => { inputTitle.current.focus() }, 100); return () => clearTimeout(timeout) } >

worked for me

**Comment by jehillert** [comment]
This is basically the same as @maXXCZ1 solution, but with an added twist.  It doesn't require setTimeout, seems to work cleanly and consistently every time, and visually there is no delay between when the TextInput appears and the modal.

Short Answer:
```tsx
import Modal from 'react-native-modal';

const myModal = (props) => {
  const ref = useRef(null);
  const [modalShown, setModalShown] = useState(false);

  return (
    <Modal onModalShow={() => setModalShown(true)} onModalWillHide={() => setModalShown(false)}>
      <View>
        {/* TextInput_A only shows when modal fully mounted. Has autofocus. */}
        {modalShown && (
          <TextInput
            autoFocus
            ref={ref}
            style={styleTextInput}
            onChangeText={(text) => setInputValue(text)}
            placeholder={placeholder}
          />
        )}
        {/* TextInput_A sits around and looks pretty in the meantime */}
        {!modalShown && (
          <TextInput
            style={styleTextInput}
            onChangeText={(text) => setInputValue(text)}
            placeholder={placeholder}
          />
        )}
      </View>
    </Modal>
  );
};

```


<details>
<summary>Long Answer</summary>

```tsx
import React, { useRef, useState, ReactNode, useEffect } from 'react';
import styled from 'styled-components/native';
import { Button } from 'react-native-paper';
import Modal, { ModalProps } from 'react-native-modal';
import { View, StyleProp, TextInput as RNGHTextInput, TextStyle, ViewStyle, StyleSheet } from 'react-native';
import { TextPaper } from '../TextPaper';
import { windowHeight } from '../../constants';

type Props = Partial<ModalProps> & {
  children?: ReactNode;
  closeModal: () => void;
  handlePressLeft: () => void;
  handlePressRight: (textInput: string) => void | Promise<void>;
  isVisible: boolean;
  labelLeft?: string;
  labelRight?: string;
  placeholder?: string;
  setIsVisible: (show: boolean) => void;
  style?: StyleProp<ViewStyle>;
  styleModalContent?: StyleProp<ViewStyle>;
  styleTextInput?: StyleProp<TextStyle>;
  title?: string;
};

const InputModal = ({
  children,
  closeModal,
  handlePressLeft,
  handlePressRight,
  isVisible,
  labelLeft = 'Cancel',
  labelRight = 'Ok',
  placeholder,
  setIsVisible,
  style,
  styleModalContent,
  styleTextInput,
  title,
  ...rest
}: Props) => {
  const [inputValue, setInputValue] = useState(title ?? '');
  const [modalShown, setModalShown] = useState(false);
  const inputRef = useRef<RNGHTextInput>(null);

  return (
    <Modal
      animationIn='fadeIn'
      isVisible={isVisible}
      useNativeDriver={true}
      style={[styles.modal, style]}
      onModalShow={() => setModalShown(true)}
      onModalWillHide={() => setModalShown(false)}
      {...rest}
    >
      <ModalContent style={styleModalContent}>
        <TextPaper.TitleMedium>{title}</TextPaper.TitleMedium>
        {modalShown && (
          <TextInput
            autoFocus
            ref={inputRef}
            style={styleTextInput}
            onChangeText={(text) => setInputValue(text)}
            placeholder={placeholder}
          />
        )}
        {!modalShown && (
          <TextInput
            style={styleTextInput}
            onChangeText={(text) => setInputValue(text)}
            placeholder={placeholder}
          />
        )}
        <ButtonRowView>
          <Button onPress={handlePressLeft}>{labelLeft}</Button>
          <Button onPress={() => handlePressRight(inputValue)}>{labelRight}</Button>
        </ButtonRowView>
      </ModalContent>
    </Modal>
  );
};

const ButtonRowView = styled(View)`
  width: 100%;
  display: flex;
  justify-content: flex-end;
  flex-direction: row;
  flex-wrap: nowrap;
`;

const ModalContent = styled(View)`
  display: flex;
  align-items: flex-start;
  background-color: ${({ theme }) => theme.colors.secondaryContainer};
  border-radius: 16px;
  padding: 16px;
  margin-horizontal: 8px;
  row-gap: 16px;
`;

const TextInput = styled(RNGHTextInput)`
  width: 100%;
  border: 2px solid ${({ theme }) => theme.colors.onPrimary};
  color: ${({ theme }) => theme.colors.onPrimary};
  background-color: ${({ theme }) => theme.colors.primary};
  padding-horizontal: 16px;
`;

const styles = StyleSheet.create({
  modal: {
    position: 'absolute',
    top: windowHeight * 0.2,
  },
});

export type { Props as InputModalProps };

export default InputModal;

```
</details>

**Comment by mozzius** [comment]
Thanks @jehillert! even though I'm not even using this library, just the build-in Modal, this is the first solution I've found that works consistently - timeout-based solutions all had race conditions on slow devices.

You can make it a bit simpler by using a `key` prop on the TextInput to force a rerender

```
key={isAndroid ? (visible ? 'visible' : 'hidden') : 'static'}
```

**Comment by rolandsfr** [comment]
Is this a react-native problem rather than react-native-modal...? Does not matter what kind of modal you are using (even custom one with View and Portal), unless the modal appearance is immediate without **any** animations transitions, the keyboard will auto-hide for some reason if input inside the modal will try to focus as soon as it mounts (aka when modal is shown). Workaround mentioned above with delaying autofocus via `setTimeout` works, but I think it's a limitation, because what if I want to focus and open keyboard (and persist it!) whilst the modal is in transition to be opened.

**Comment by ErAz7** [comment]
might be a better idea to use `onLayout` instead of `setTimeout`
